// Generated by CoffeeScript 1.6.3
(function() {
  window.puts = function(output) {
    return console.log(output);
  };

  window.setUsername = function(username) {
    return window.location.hash = username;
  };

  window.getUsername = function() {
    if (window.location.hash === "") {
      return false;
    } else {
      return window.location.hash.slice(1);
    }
  };

}).call(this);
