// Generated by CoffeeScript 1.6.3
(function() {
  var puts, randomNum;

  randomNum = function(upper_limit) {
    return Math.floor((Math.random() * upper_limit) + 1);
  };

  puts = function(output) {
    return console.log(output);
  };

  $(function() {
    var $github_username, $github_username_input, dataset, h, svg, w;
    h = 500;
    w = 500;
    svg = d3.select("body").append("svg").attr("height", h).attr("width", w).attr("fill", "red");
    $github_username = $(".github_username");
    $github_username_input = $github_username.find("input");
    dataset = [];
    return $github_username.on("submit", function(event) {
      var url, username;
      event.preventDefault();
      username = $github_username_input.val();
      $github_username_input.val("");
      url = "https://api.github.com/users/" + username + "/repos";
      return $.ajax({
        url: url,
        type: 'get',
        dataType: 'jsonp',
        crossDomain: true,
        success: function(data) {
          dataset = data.data;
          puts(dataset);
          return svg.selectAll("rect").data(dataset).enter().append("rect").attr("x", function(d, i) {
            return (w / dataset.length) * i;
          }).attr("y", function(d, i) {
            return h - d.size;
          }).attr("width", (w / dataset.length) - 3).attr("height", function(d, i) {
            return d.size;
          }).attr("fill", "teal");
        }
      });
    });
  });

}).call(this);
