// Generated by CoffeeScript 1.6.3
(function() {
  var dataset;

  dataset = [5, 10, 15, 20, 25];

  d3.select("body").selectAll("p").data(dataset).enter().append("p").text(function(data) {
    var num;
    num = parseInt(data);
    if (num > 10) {
      return "" + num + " is greater than ten";
    } else {
      return "" + num + " is less than or equal to ten";
    }
  }).style("color", function(d) {
    if (d > 15) {
      return "red";
    } else {
      return "black";
    }
  });

}).call(this);
